import { describe, expect, test } from 'vitest';
import { colorsFromUrlParams, colorsToUrlParams } from '../../../../src/react/components/color/colorPickerUrlParams';
import { CSS_VARIABLES_KEYS } from '../../../../src/react/enums/cssVariablesKeys';

describe('colorPickerColorsBase64 - sanity', () => {
  test('sanity check - colors list known and in specific order', () => {
    expect(Object.values(CSS_VARIABLES_KEYS)).toStrictEqual([
      CSS_VARIABLES_KEYS.PRIMARY_COLOR,
      CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK,
      CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT,
      CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR,
      CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK,
      CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT,
      CSS_VARIABLES_KEYS.SECONDARY_COLOR,
      CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK,
      CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT,
      CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR,
      CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK,
      CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT,
      CSS_VARIABLES_KEYS.ACCENT_COLOR,
      CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK,
      CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT,
      CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR,
      CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK,
      CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT,
      CSS_VARIABLES_KEYS.GRAY_COLOR,
      CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR,
      CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK,
      CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR,
    ]);
  });
});

describe('colorPickerColorsBase64 - colorsToUrlParams', () => {
  test('single color', () => {
    const colors = {
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR]: '#abcdef',
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK]: undefined,
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT]: undefined,
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR]: undefined,
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK]: undefined,
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT]: undefined,
      [CSS_VARIABLES_KEYS.ACCENT_COLOR]: undefined,
      [CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK]: undefined,
      [CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT]: undefined,
      [CSS_VARIABLES_KEYS.GRAY_COLOR]: undefined,
      [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR]: undefined,
      [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK]: undefined,
      [CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR]: undefined,
    };
    expect(colorsToUrlParams(colors)).toEqual('colors=v1abcdef_____________________');
  });

  test('all colors', () => {
    const colors = {
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR]: '#abcdef',
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK]: '#012345',
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT]: '#ffffff',
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR]: '#987654',
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK]: '#f1f1f1',
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT]: '#444444',
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR]: '#eeeeee',
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK]: '#0f0f0f',
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT]: '#111111',
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR]: '#222222',
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK]: '#f2f2f2',
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT]: '#aa1144',
      [CSS_VARIABLES_KEYS.ACCENT_COLOR]: '#333333',
      [CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK]: '#f3f3f3',
      [CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT]: '#bbaa77',
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR]: '#aaaaaa',
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK]: '#f4f4f4',
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT]: '#555555',
      [CSS_VARIABLES_KEYS.GRAY_COLOR]: '#3d3d3d',
      [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR]: '#ccaa77',
      [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK]: '#f6f6f6',
      [CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR]: '#d06555',
    };
    expect(colorsToUrlParams(colors)).toEqual('colors=v1abcdef012345ffffff987654f1f1f1444444eeeeee0f0f0f111111222222f2f2f2aa1144333333f3f3f3bbaa77aaaaaaf4f4f45555553d3d3dccaa77f6f6f6d06555');
  });

  test('mixed colors missing', () => {
    const colors = {
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR]: '#abcdef',
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK]: '',
      [CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT]: null,
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR]: '',
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK]: '#f1f1f1',
      [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT]: '#222',
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR]: '#eee',
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK]: '#0f0f0f',
      [CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT]: '#111111',
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR]: '#222222',
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK]: null,
      [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT]: '#444444',
      [CSS_VARIABLES_KEYS.ACCENT_COLOR]: '#333333',
      [CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK]: null,
      [CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT]: null,
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR]: null,
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK]: '#e1e1e1',
      [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT]: null,
      [CSS_VARIABLES_KEYS.GRAY_COLOR]: '#3c3c3c',
      [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR]: null,
      [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK]: '#ccc',
      [CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR]: null,
    };
    expect(colorsToUrlParams(colors)).toEqual('colors=v1abcdef___f1f1f1222222eeeeee0f0f0f111111222222_444444333333___e1e1e1_3c3c3c_cccccc_');
  });
});

describe('colorPickerColorsBase64 - colorsFromUrlParams', () => {
  test('single color', () => {
    expect(colorsFromUrlParams('colors=v1abcdef_____________________'))
      .toStrictEqual({
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR]: '#abcdef',
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.ACCENT_COLOR]: null,
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_COLOR]: null,
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR]: null,
      });
  });

  test('all colors', () => {
    expect(colorsFromUrlParams('colors=v1abcdef012345ffffff987654f1f1f1444444eeeeee0f0f0f111111222222f2f2f2aa1144333333f3f3f3bbaa77aaaaaaf4f4f45555553d3d3dccaa77f6f6f6d06555'))
      .toStrictEqual({
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR]: '#abcdef',
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK]: '#012345',
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT]: '#ffffff',
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR]: '#987654',
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK]: '#f1f1f1',
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT]: '#444444',
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR]: '#eeeeee',
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK]: '#0f0f0f',
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT]: '#111111',
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR]: '#222222',
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK]: '#f2f2f2',
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT]: '#aa1144',
        [CSS_VARIABLES_KEYS.ACCENT_COLOR]: '#333333',
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK]: '#f3f3f3',
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT]: '#bbaa77',
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR]: '#aaaaaa',
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK]: '#f4f4f4',
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT]: '#555555',
        [CSS_VARIABLES_KEYS.GRAY_COLOR]: '#3d3d3d',
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR]: '#ccaa77',
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK]: '#f6f6f6',
        [CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR]: '#d06555',
      });
  });

  test('no parameter in url', () => {
    expect(colorsFromUrlParams(''))
      .toStrictEqual({
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.ACCENT_COLOR]: null,
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_COLOR]: null,
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR]: null,
      });
  });

  test('mixed colors missing', () => {
    expect(colorsFromUrlParams('colors=v1abcdef_____eeeeee0f0f0f111111222222_aa1144333333_____3c3c3cc1a155_d06555'))
      .toStrictEqual({
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR]: '#abcdef',
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.PRIMARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_PRIMARY_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR]: '#eeeeee',
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_DARK]: '#0f0f0f',
        [CSS_VARIABLES_KEYS.SECONDARY_COLOR_LIGHT]: '#111111',
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR]: '#222222',
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_SECONDARY_COLOR_LIGHT]: '#aa1144',
        [CSS_VARIABLES_KEYS.ACCENT_COLOR]: '#333333',
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.ACCENT_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.GRAY_ON_ACCENT_COLOR_LIGHT]: null,
        [CSS_VARIABLES_KEYS.GRAY_COLOR]: '#3c3c3c',
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR]: '#c1a155',
        [CSS_VARIABLES_KEYS.HEADER_PRIMARY_COLOR_DARK]: null,
        [CSS_VARIABLES_KEYS.HEADER_GRAY_ON_PRIMARY_COLOR]: '#d06555',
      });
  });
});
