name: Build and Publish utah-header BETA
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🐣
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Setup Node 🐔
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Install 🪚
        run: |
          npm install
      - name: NPM header Build 🔨
        run: |
          npm run buildForNPM
      - name: Build Types 🪚
        run: |
          npm run buildTypesHeader
      - name: NPM Publish 🏠
        run: |
          npm run publishHeaderBeta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
