name: Build and Publish library BETA
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🐣
        uses: actions/checkout@v6
      - name: Setup Node 🐔
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Install 🪚
        run: |
          npm install
      - name: NPM Build 🔨
        run: |
          npm run buildLibrary
      - name: Build Types 🪚
        run: |
          npm run buildTypesLibrary
      - name: NPM Publish 🏠
        run: |
          npm run publishLibraryBeta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
